const DressesData = [
  {
    id:"dress-1",
    img: require(`./Dresses images/dress-1.jpg`),
    head: "BIBA",
    description:
      "Blue raw silk kalider paired with pants and an organza dupatta",
    price: "949",
    prePrice: "1,999 ",
    discount: " (-53%)",
  },
  {
    id:"dress-2",
    img: require(`./Dresses images/dress-2.jpg`),
    head: "Missprint Designs",
    description:
      "a printed gathered Anarkali with stole dupatta. Color: Navy Fabric: Tussar Silk",
    price: "1,700",
    prePrice: "2,550 ",
    discount: " (-53%)",
  },
  {
    id:"dress-3",
    img: require(`./Dresses images/dress-3.jpg`),
    head: "Andaaz Fashion",
    description: "Zari Embroidered Georgette Prussian Blue Eid Anarkali Suit",
    price: "1,049",
    prePrice: "2,499 ",
    discount: " (-58%)",
  },
  {
    id:"dress-4",
    img: require(`./Dresses images/dress-4.jpg`),
    head: "W for Women",
    description:"for Sea green Velvet shirt bell bottom trouser with organza dupatta suit",
    price: "999",
    prePrice: "2,500 ",
    discount: " (-60%)",
  },
  {
    id:"dress-5",
    img: require(`./Dresses images/dress-5.jpg`),
    head: "Maharani Couture",
    description: "Lavaya Women Drawstring Side Split Skirt with White Top",
    price: "1,999",
    prePrice: "3,999 ",
    discount: " (-50%)",
  },
  {
    id:"dress-6",
    img: require(`./Dresses images/dress-6.jpg`),
    head: "Sahasya Suits",
    description: " hand-embroidered wedding wear in colors inspired by nature",
    price: "2,900",
    prePrice: "3,999 ",
    discount: " (-27.5%)",
  },
  {
    id:"dress-7",
    img: require(`./Dresses images/dress-7.jpg`),
    head: "Tulsi Silks",
    description: "a fusion of the traditional saree with pants kjldgbjkjzslgj",
    price: "3999",
    prePrice: "4,799 ",
    discount: " (-20%)",
  },
  {
    id:"dress-8",
    img: require(`./Dresses images/dress-8.jpg`),
    head: "Sareeka Studios",
    description: " Gorgeous Embroidered and Resham Work Grey Anarkali Suit",
    price: "1,999",
    prePrice: "5,999 ",
    discount: " (-66%)",
  },
  {
    id:"dress-9",
    img: require(`./Dresses images/dress-9.jpg`),
    head: "Azruma",
    description:
      "Azruma winter dress fashion long sleeve v neck women elegant turtleneck dress",
    price: "3999",
    prePrice: "4,799 ",
    discount: " (-20%)",
  },
  {
    id:"dress-10",
    img: require(`./Dresses images/dress-10.jpg`),
    head: "SHEIN",
    description: "SHEIN Twist Front Cami Bodycon Dress & shrug top",
    price: "1,999",
    prePrice: "5,999 ",
    discount: " (-66%)",
  },
  {
    id:"dress-11",
    img: require(`./Dresses images/dress-11.jpg`),
    head: "Oalka",
    description: "Women's High Neck Crop Top Sleeveless Tank Tops Shirt",
    price: "3999",
    prePrice: "4,799 ",
    discount: " (-20%)",
  },
  {
    id:"dress-12",
    img: require(`./Dresses images/dress-12.jpg`),
    head: "Am Fashions",
    description:
      "Micro-Dot Print Wrap-Around Ruffled sleeves Tie-up at the back Dress",
    price: "947",
    prePrice: "4,999 ",
    discount: " (-81%)",
  },
];
export default DressesData;
