const kurtisData = [
  {
    id:"kurti-1",
    img: require(`./Kurtis images/kurti-1.jpg`),
    head: "CRAFT & FASHION",
    description: "A-Line Knee-Length Casual Wear kurti kfbdlkld",
    price: "949",
    prePrice: "1,999 ",
    discount: " (-53%)",
  },
  {
    id:"kurti-2",
    img: require(`./Kurtis images/kurti-2.jpg`),
    head: "Fibre-2-Fashion",
    description: "Designer Kurtis - Buy Kurti Online, Women Kurta Shopping",
    price: "1,700",
    prePrice: "2,550 ",
    discount: " (-53%)",
  },
  {
    id:"kurti-3",
    img: require(`./Kurtis images/kurti-3.jpg`),
    head: "Kesari Textile",
    description: "Rayon Blend Stitched Anarkali Kurti for Womenk",
    price: "1,049",
    prePrice: "2,499 ",
    discount: " (-58%)",
  },
  {
    id:"kurti-4",
    img: require(`./Kurtis images/kurtis-4.jpg`),
    head: "QueensVilla",
    description:"This Kurti Set suitable for Partywear,Small Functions get together",
    price: "999",
    prePrice: "2,500 ",
    discount: " (-60%)",
  },
  {
    id:"kurti-5",
    img: require(`./Kurtis images/kurti-5.jpg`),
    head: "Priya Trends",
    description:"Priya Trend Heavy Rayon 14kg Women's Kurti Vol 3 jkslbljs soipdhblk sidln",
    price: "1,999",
    prePrice: "3,999 ",
    discount: " (-50%)",
  },
  {
    id:"kurti-6",
    img: require(`./Kurtis images/kurti-6.jpg`),
    head: "LT Fabrics Kurtis",
    description: "embroidered inner heavy santoon white with grey colour kurti",
    price: "2,900",
    prePrice: "3,999 ",
    discount: " (-27.5%)",
  },
  {
    id:"kurti-7",
    img: require(`./Kurtis images/kurti-7.jpg`),
    head: "BIBA",
    description: "Office Wear Kurta Designs for Women to try",
    price: "3999",
    prePrice: "4,799 ",
    discount: " (-20%)",
  },
  {
    id:"kurti-8",
    img: require(`./Kurtis images/kurti-8.jpg`),
    head: "FabCartz",
    description: "hot & latest Kurtis & Kurtas Women Pink Solid Embrodried",
    price: "1,999",
    prePrice: "5,999 ",
    discount: " (-66%)",
  },
  {
    id:"kurti-9",
    img: require(`./Kurtis images/kurti-9.jpg`),
    head: "Label D11",
    description: "Meira Gorgeous Designer Women's Kurtis Vol 13",
    price: "3999",
    prePrice: "4,799 ",
    discount: " (-20%)",
  },
  {
    id:"kurti-10",
    img: require(`./Kurtis images/kurti-10.jpg`),
    head: "Jaipur Attire",
    description: "jhgsdjh igfkdh igfdbh uihsdbjkb iuhodfb ijbdf iudf hfbdb",
    price: "1,999",
    prePrice: "5,999 ",
    discount: " (-66%)",
  },
  {
    id:"kurti-11",
    img: require(`./Kurtis images/kurti-11.jpg`),
    head: "Generic",
    description: "hot & latest Kurtis & Kurtas Gorgeous Designer Kurti",
    price: "3999",
    prePrice: "4,799 ",
    discount: " (-20%)",
  },
  {
    id:"kurti-12",
    img: require(`./Kurtis images/kurti-12.jpg`),
    head: "Amrutam Fab",
    description: "kjdbj jkbd ilhbdk lbdj hfbdk ulkbdla jljsbdj kjbsdk jlsbd",
    price: "947",
    prePrice: "4,999 ",
    discount: " (-81%)",
  },
];

export default kurtisData;
