const SpecialsData = [
  {
    id:"special-1",
    img: require(`./Specials images/specials-1.jpg`),
    head: "BIBA",
    description: "Teal Cotton Flared Printed Dress",
    price: "2,399",
    prePrice: "3,999 ",
    discount: " (-40%)",
  },
  { 
    id:"special-2",
    img: require(`./Specials images/specials-2.jpg`),
    head: "K.S.Trading",
    description: " Beautiful Top Skirt Set for the Festive Season for Girls",
    price: "1,700",
    prePrice: "2,550 ",
    discount: " (-53%)",
  },
  {
    id:"special-3",
    img: require(`./Specials images/specials-3.jpg`),
    head: "Sashay Boutique",
    description: "Yashodhara crop top paired with flaired palazzos",
    price: "1,022",
    prePrice: "3,299 ",
    discount: " (-69%)",
  },
  {
    id:"special-4",
    img: require(`./Specials images/specials-4.jpg`),
    head: "Mohey Fashions",
    description: "Mohey Vibrant Blue Lehenga for Women",
    price: "2,246",
    prePrice: "3,899 ",
    discount: " (-49%)",
  },
  {
    id:"special-5",
    img: require(`./Specials images/specials-5.jpg`),
    head: "Indian Clothing",
    description:"Cotton Designer Party Wear Indowestern Kurti In Cream With Slit",
    price: "1,999",
    prePrice: "3,999 ",
    discount: " (-50%)",
  },
  {
    id:"special-6",
    img: require(`./Specials images/specials-6.jpg`),
    head: "W",
    description: "Print Front Open Viscose Womens Layered Dress",
    price: "1,409",
    prePrice: "2,999 ",
    discount: " (-53%)",
  },
  {
    id:"special-7",
    img: require(`./Specials images/specials-7.jpg`),
    head: "Royal Anarkali",
    description:"Streamlined Grey Color Heavy Embroidered Net & Full Moti Work Suit for Women's ",
    price: "3999",
    prePrice: "4,799 ",
    discount: " (-20%)",
  },
  {
    id:"special-8",
    img: require(`./Specials images/specials-8.jpg`),
    head: "Generic",
    description: "Purple Embroidered Semi Stitched Lehenga Choli With Dupatta",
    price: "1,999",
    prePrice: "5,999 ",
    discount: " (-66%)",
  },
  {
    id:"special-9",
    img: require(`./Specials images/specials-9.jpg`),
    head: "Azruma",
    description: "Suits For Women, Suit Designs, Salwar Suits",
    price: "3999",
    prePrice: "4,799 ",
    discount: " (-20%)",
  },
  {
    id:"special-10",
    img: require(`./Specials images/specials-10.jpg`),
    head: "Chotibuti",
    description: "Women's Polka Dot Cold Shoulder Top with Ruffle Detail",
    price: "1,949",
    prePrice: "2,999 ",
    discount: " (-35%)",
  },
  {
    id:"special-11",
    img: require(`./Specials images/specials-11.jpg`),
    head: "Modarue",
    description: "Modarue Stylish Womens Sleeveles top with jeans",
    price: "1,700",
    prePrice: "2,550 ",
    discount: " (-53%)",
  },
  {
    id:"special-12",
    img: require(`./Specials images/specials-12.jpg`),
    head: "Sashay Boutique",
    description:
      "Black Wrap-Front-Cut Cotton Crop Top with Blue Damaged Jeans",
    price: "2,022",
    prePrice: "4,299 ",
    discount: " (-53%)",
  },
];
export default SpecialsData;
